/**
 * Fixed-income analytics — pure functions, no I/O.
 *
 * Prices are expressed per 100 of par ("clean price", e.g. 98.50). Dollar
 * figures (accrued, income, dv01) are scaled to the held face value.
 *
 * Pricing follows the standard street convention: the dirty price is the PV of
 * the remaining cash flows discounted at the periodic yield, with the first
 * period fractionally discounted by the settlement/coupon day-count weight;
 * the clean price is the dirty price minus accrued interest.
 */

import type { DayCount } from "./types";

export interface BondSpec {
  /** Face value held, in dollars of par (= `shares` under the face-value trick). */
  faceValue: number;
  /** Annual coupon rate, percent of par (e.g. 4.25). 0 for zero-coupon. */
  couponRate: number;
  /** Coupon payments per year (2 = semiannual). */
  couponFreq: number;
  /** Maturity date (ISO yyyy-mm-dd). */
  maturityDate: string;
  dayCount?: DayCount;
}

export interface BondAnalytics {
  cleanPrice: number;
  dirtyPrice: number;
  accrued: number;
  ytm: number;
  currentYield: number;
  modifiedDuration: number;
  macaulayDuration: number;
  dv01: number;
  annualIncome: number;
  nextCouponDate: string | null;
  nextCouponAmount: number;
}

const MS_PER_DAY = 86_400_000;

function toDate(iso: string): Date {
  // Parse as UTC midnight so day-count math is stable regardless of timezone.
  const [y, m, d] = iso.slice(0, 10).split("-").map(Number);
  return new Date(Date.UTC(y, (m || 1) - 1, d || 1));
}

function actualDays(a: Date, b: Date): number {
  return Math.round((b.getTime() - a.getTime()) / MS_PER_DAY);
}

/** 30/360 US day count between two dates. */
function days360(a: Date, b: Date): number {
  let d1 = a.getUTCDate();
  let d2 = b.getUTCDate();
  const m1 = a.getUTCMonth() + 1;
  const m2 = b.getUTCMonth() + 1;
  const y1 = a.getUTCFullYear();
  const y2 = b.getUTCFullYear();
  if (d1 === 31) d1 = 30;
  if (d2 === 31 && d1 === 30) d2 = 30;
  return (y2 - y1) * 360 + (m2 - m1) * 30 + (d2 - d1);
}

/** Subtract n whole months from a date, clamping the day to month length. */
function addMonths(date: Date, months: number): Date {
  const y = date.getUTCFullYear();
  const m = date.getUTCMonth();
  const d = date.getUTCDate();
  const target = new Date(Date.UTC(y, m + months, 1));
  const lastDay = new Date(Date.UTC(target.getUTCFullYear(), target.getUTCMonth() + 1, 0)).getUTCDate();
  target.setUTCDate(Math.min(d, lastDay));
  return target;
}

/**
 * Future coupon dates strictly after `settle`, in ascending order, ending at
 * maturity. Generated by stepping back from maturity by the coupon period.
 */
export function couponSchedule(maturity: Date, freq: number, settle: Date): Date[] {
  const step = Math.max(1, Math.round(12 / freq));
  const dates: Date[] = [];
  let d = new Date(maturity.getTime());
  // Walk backwards to just past settle, collecting dates.
  while (d.getTime() > settle.getTime()) {
    dates.push(new Date(d.getTime()));
    d = addMonths(d, -step);
  }
  return dates.reverse();
}

/** Day-count fraction of a coupon period, used to weight the first (stub) period. */
function periodWeight(prev: Date, next: Date, settle: Date, dc: DayCount): number {
  if (dc === "30/360") {
    const whole = days360(prev, next) || 1;
    return days360(settle, next) / whole;
  }
  // actual/actual and actual/365 both weight by actual days within the period.
  const whole = actualDays(prev, next) || 1;
  return actualDays(settle, next) / whole;
}

interface Priced {
  clean: number;
  dirty: number;
  accrued: number; // per 100 of par
  cashflowPeriods: number[]; // time (in periods) of each future cash flow
  cashflows: number[]; // per 100 of par
}

/**
 * Clean/dirty price (per 100) and accrued (per 100) for a given annual yield %.
 * `annualYield` is a nominal yield compounded `freq` times per year.
 */
function priceFromYield(spec: BondSpec, annualYieldPct: number, settle: Date): Priced {
  const freq = Math.max(1, spec.couponFreq || 2);
  const dc = spec.dayCount ?? "actual/actual";
  const maturity = toDate(spec.maturityDate);
  const couponPer100 = spec.couponRate / freq; // coupon per period, per 100 of par
  const y = annualYieldPct / 100 / freq; // periodic yield

  const schedule = couponSchedule(maturity, freq, settle);
  if (schedule.length === 0) {
    // Matured (or settles on/after maturity): worth redemption + final coupon.
    return { clean: 100, dirty: 100 + couponPer100, accrued: couponPer100, cashflowPeriods: [], cashflows: [] };
  }

  const nextCoupon = schedule[0];
  const prevCoupon = addMonths(nextCoupon, -Math.max(1, Math.round(12 / freq)));
  const w = Math.min(1, Math.max(0, periodWeight(prevCoupon, nextCoupon, settle, dc))); // fraction of period remaining

  const periods: number[] = [];
  const flows: number[] = [];
  let dirty = 0;
  for (let k = 0; k < schedule.length; k++) {
    const t = w + k; // time to this cash flow, in periods
    const isLast = k === schedule.length - 1;
    const cf = couponPer100 + (isLast ? 100 : 0);
    const df = 1 / Math.pow(1 + y, t);
    dirty += cf * df;
    periods.push(t);
    flows.push(cf);
  }
  const accrued = couponPer100 * (1 - w); // fraction of the period already elapsed
  return { clean: dirty - accrued, dirty, accrued, cashflowPeriods: periods, cashflows: flows };
}

/** Solve for the annual yield % that reproduces a given clean price, via bisection. */
export function yieldToMaturity(spec: BondSpec, cleanPrice: number, settle: Date): number {
  let lo = -0.5; // allow slightly negative yields (short bills)
  let hi = 100;
  const target = cleanPrice;
  // Ensure the target is bracketed; price is monotically decreasing in yield.
  for (let i = 0; i < 100; i++) {
    const mid = (lo + hi) / 2;
    const p = priceFromYield(spec, mid, settle).clean;
    if (Math.abs(p - target) < 1e-7) return mid;
    if (p > target) lo = mid;
    else hi = mid;
  }
  return (lo + hi) / 2;
}

/**
 * Full analytics given a known clean price (from the curve, par, cost, or a
 * manual mark). Returns dollar figures scaled to the held face value.
 */
export function bondAnalytics(spec: BondSpec, cleanPrice: number, asOf: Date): BondAnalytics {
  const freq = Math.max(1, spec.couponFreq || 2);
  const settle = asOf;
  const priced = priceFromYield(spec, 0, settle); // reused only for schedule/accrued shape
  const ytm = yieldToMaturity(spec, cleanPrice, settle);

  // Recompute cash flows at the solved yield for duration.
  const atYield = priceFromYield(spec, ytm, settle);
  const y = ytm / 100 / freq;
  let weighted = 0;
  for (let k = 0; k < atYield.cashflowPeriods.length; k++) {
    const t = atYield.cashflowPeriods[k];
    const pv = atYield.cashflows[k] / Math.pow(1 + y, t);
    weighted += (t / freq) * pv; // time in years
  }
  const macaulay = atYield.dirty > 0 ? weighted / atYield.dirty : 0;
  const modified = macaulay / (1 + y);

  const faceScale = spec.faceValue / 100;
  const accrued = priced.accrued * faceScale;
  const dirtyValue = (cleanPrice + priced.accrued) * faceScale;
  const annualIncome = spec.faceValue * (spec.couponRate / 100);
  const currentYield = cleanPrice > 0 ? (spec.couponRate / cleanPrice) * 100 : 0;
  const dv01 = modified * 0.0001 * dirtyValue; // $ change per 1bp

  const schedule = couponSchedule(toDate(spec.maturityDate), freq, settle);
  const nextCouponDate = schedule.length ? isoOf(schedule[0]) : null;
  const nextCouponAmount = schedule.length ? spec.faceValue * (spec.couponRate / 100) / freq : 0;

  return {
    cleanPrice,
    dirtyPrice: cleanPrice + priced.accrued,
    accrued,
    ytm,
    currentYield,
    modifiedDuration: modified,
    macaulayDuration: macaulay,
    dv01,
    annualIncome,
    nextCouponDate,
    nextCouponAmount,
  };
}

/** Clean price (per 100) implied by an annual yield % — used for curve pricing. */
export function priceAtYield(spec: BondSpec, annualYieldPct: number, asOf: Date): number {
  return priceFromYield(spec, annualYieldPct, asOf).clean;
}

/** Years from `asOf` to maturity (actual/365), floored at 0. */
export function yearsToMaturity(maturityDate: string, asOf: Date): number {
  const days = actualDays(asOf, toDate(maturityDate));
  return Math.max(0, days / 365);
}

function isoOf(d: Date): string {
  return d.toISOString().slice(0, 10);
}
