import type { Holding } from "./types";


export const HOLDINGS: Holding[] = [
  /* Brokerage */
  {
    id: "b-aapl",
    ticker: "AAPL",
    name: "Apple Inc.",
    sector: "Technology",
    shares: 25,
    costBasis: 167.40,
    currentPrice: 213.80,
    account: "brokerage",
    notes: "Core position. Hold through product cycle.",
  },
  {
    id: "b-msft",
    ticker: "MSFT",
    name: "Microsoft Corp.",
    sector: "Technology",
    shares: 12,
    costBasis: 318.50,
    currentPrice: 422.10,
    account: "brokerage",
  },
  {
    id: "b-voo",
    ticker: "VOO",
    name: "Vanguard S&P 500 ETF",
    sector: "Index",
    shares: 10,
    costBasis: 420.00,
    currentPrice: 518.40,
    account: "brokerage",
  },
  {
    id: "b-nvda",
    ticker: "NVDA",
    name: "NVIDIA Corp.",
    sector: "Semiconductors",
    shares: 8,
    costBasis: 492.30,
    currentPrice: 874.60,
    account: "brokerage",
    notes: "Trim if above $950.",
  },
  {
    id: "b-jpm",
    ticker: "JPM",
    name: "JPMorgan Chase",
    sector: "Financials",
    shares: 15,
    costBasis: 178.90,
    currentPrice: 224.30,
    account: "brokerage",
  },
  {
    id: "b-brkb",
    ticker: "BRK.B",
    name: "Berkshire Hathaway B",
    sector: "Financials",
    shares: 20,
    costBasis: 338.10,
    currentPrice: 442.50,
    account: "brokerage",
  },
  {
    id: "b-cop",
    ticker: "COP",
    name: "ConocoPhillips",
    sector: "Energy",
    shares: 18,
    costBasis: 112.40,
    currentPrice: 98.70,
    account: "brokerage",
    notes: "Down on crude weakness. Watch $95 support.",
  },
  {
    id: "b-tlt",
    ticker: "TLT",
    name: "iShares 20+ Year Treasury",
    sector: "Fixed Income",
    shares: 30,
    costBasis: 98.20,
    currentPrice: 86.40,
    account: "brokerage",
    notes: "Rate hedge. Duration risk.",
  },

  /* Roth IRA */
  {
    id: "r-vti",
    ticker: "VTI",
    name: "Vanguard Total Market ETF",
    sector: "Index",
    shares: 22,
    costBasis: 218.30,
    currentPrice: 262.90,
    account: "roth",
  },
  {
    id: "r-vxus",
    ticker: "VXUS",
    name: "Vanguard Total Intl ETF",
    sector: "Index",
    shares: 18,
    costBasis: 54.80,
    currentPrice: 61.20,
    account: "roth",
    notes: "International diversification.",
  },
  {
    id: "r-avuv",
    ticker: "AVUV",
    name: "Avantis US Small Cap Value",
    sector: "Small Cap",
    shares: 14,
    costBasis: 86.40,
    currentPrice: 102.80,
    account: "roth",
  },
  {
    id: "r-googl",
    ticker: "GOOGL",
    name: "Alphabet Inc.",
    sector: "Technology",
    shares: 5,
    costBasis: 132.60,
    currentPrice: 187.40,
    account: "roth",
  },
  {
    id: "r-meta",
    ticker: "META",
    name: "Meta Platforms Inc.",
    sector: "Technology",
    shares: 4,
    costBasis: 298.40,
    currentPrice: 534.20,
    account: "roth",
  },
];

export const LAST_SYNC = new Date(Date.now() - 1000 * 60 * 14); // 14 min ago

/* Simulated today's change — in a real app this comes from the market data API */
export const TODAY_CHANGES: Record<string, number> = {
  AAPL:  0.84,
  MSFT:  2.14,
  VOO:   1.22,
  NVDA: -3.40,
  JPM:   0.66,
  "BRK.B": 0.38,
  COP:  -1.12,
  TLT:   0.20,
  VTI:   1.05,
  VXUS:  0.42,
  AVUV:  0.88,
  GOOGL: 1.74,
  META: -0.96,
};
