// One-time generator: pulls the canonical S&P 500 constituent list (symbol, name,
// GICS sector) and enriches each with a current market cap (via Yahoo's crumbed
// batch quote), then writes lib/sp500.ts. Re-run periodically to refresh caps.
//
//   node scripts/gen-sp500.mjs
//
// Caps drive tile AREA only (stable layout, like the futures WEIGHTS); live %
// change drives color at runtime via /api/sp500 (spark). So slightly-stale caps
// are fine — relative sizing barely moves month to month.

import { writeFileSync } from "node:fs";

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";
const CSV_URL =
  "https://raw.githubusercontent.com/datasets/s-and-p-500-companies/main/data/constituents.csv";

// Yahoo uses dashes where the canonical list uses dots (BRK.B → BRK-B).
const toYahoo = (s) => s.replace(/\./g, "-");

// Parse one CSV line respecting quoted fields (HQ location contains commas).
function parseLine(line) {
  const out = [];
  let cur = "";
  let q = false;
  for (const ch of line) {
    if (ch === '"') q = !q;
    else if (ch === "," && !q) { out.push(cur); cur = ""; }
    else cur += ch;
  }
  out.push(cur);
  return out;
}

async function getAuth() {
  const cookieRes = await fetch("https://fc.yahoo.com", { headers: { "User-Agent": UA } });
  const setCookies = cookieRes.headers.getSetCookie?.() ?? [];
  const cookie = setCookies.map((c) => c.split(";")[0]).join("; ");
  const crumbRes = await fetch("https://query1.finance.yahoo.com/v1/test/getcrumb", {
    headers: { "User-Agent": UA, Cookie: cookie },
  });
  const crumb = (await crumbRes.text()).trim();
  if (!crumb || crumb.includes("<")) throw new Error("no crumb");
  return { cookie, crumb };
}

async function main() {
  console.error("Fetching constituents…");
  const csv = await (await fetch(CSV_URL)).text();
  const rows = csv.trim().split("\n").slice(1).map(parseLine);
  const list = rows.map((r) => ({
    symbol: toYahoo(r[0].trim()),
    name: r[1].trim(),
    sector: r[2].trim(),
  }));
  console.error(`  ${list.length} names`);

  const { cookie, crumb } = await getAuth();
  console.error("Got crumb. Fetching market caps in batches…");

  const capBySym = new Map();
  const BATCH = 50;
  for (let i = 0; i < list.length; i += BATCH) {
    const batch = list.slice(i, i + BATCH);
    const syms = batch.map((b) => b.symbol).join(",");
    const url = `https://query1.finance.yahoo.com/v7/finance/quote?symbols=${encodeURIComponent(syms)}&crumb=${encodeURIComponent(crumb)}`;
    try {
      const res = await fetch(url, { headers: { "User-Agent": UA, Cookie: cookie } });
      const json = await res.json();
      for (const q of json?.quoteResponse?.result ?? []) {
        if (q.symbol && typeof q.marketCap === "number") capBySym.set(q.symbol, q.marketCap);
      }
      console.error(`  ${Math.min(i + BATCH, list.length)}/${list.length}  (+${json?.quoteResponse?.result?.length ?? 0})`);
    } catch (e) {
      console.error(`  batch ${i} failed: ${e.message}`);
    }
    await new Promise((r) => setTimeout(r, 200));
  }

  // capB in billions, 2dp. Fallback 5B for any name Yahoo didn't return (keeps it
  // on the map as a small tile rather than dropping it).
  const enriched = list
    .map((x) => ({ ...x, capB: capBySym.has(x.symbol) ? +(capBySym.get(x.symbol) / 1e9).toFixed(2) : 5 }))
    .sort((a, b) => b.capB - a.capB);

  const missing = enriched.filter((x) => !capBySym.has(x.symbol)).map((x) => x.symbol);
  console.error(`Missing caps (fallback 5B): ${missing.length ? missing.join(", ") : "none"}`);

  const ts = `// AUTO-GENERATED by scripts/gen-sp500.mjs — do not edit by hand.
// S&P 500 constituents with GICS sector + market cap (USD billions).
// capB drives heatmap tile AREA (stable layout); live % change drives color
// at runtime via /api/sp500. Re-run the script to refresh caps.
// Generated from ${enriched.length} constituents.

export interface Sp500Member {
  symbol: string;   // Yahoo symbol (dashes, e.g. BRK-B)
  name:   string;
  sector: string;   // GICS sector
  capB:   number;   // market cap, USD billions
}

export const SP500: Sp500Member[] = ${JSON.stringify(enriched, null, 0)
    .replace(/\},\{/g, "},\n  {")
    .replace(/^\[/, "[\n  ")
    .replace(/\]$/, ",\n]")};

// GICS sectors present, largest aggregate cap first (display order).
export const SP500_SECTORS: string[] = ${JSON.stringify(
    [...enriched.reduce((m, x) => m.set(x.sector, (m.get(x.sector) ?? 0) + x.capB), new Map())]
      .sort((a, b) => b[1] - a[1])
      .map(([s]) => s),
  )};
`;

  writeFileSync(new URL("../lib/sp500.ts", import.meta.url), ts);
  console.error(`Wrote lib/sp500.ts (${enriched.length} members).`);
}

main().catch((e) => { console.error(e); process.exit(1); });
