import { NextResponse, type NextRequest } from "next/server";
import { createClient } from "@/lib/supabase/server";

/* Monthly report archive for the Accounts tab. Reports are generated by the
   snapshot cron (see lib/monthly-reports.ts) — this route only reads them.

     GET            → all reports for the latest period + the period list
     GET ?period=   → all reports for that period (YYYY-MM)

   Returns { periods, period, reports } where reports carry the full payload
   for every account (the UI filters by the sidebar's selected account). */

export async function GET(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const periodParam = request.nextUrl.searchParams.get("period");
  if (periodParam && !/^\d{4}-(0[1-9]|1[0-2])$/.test(periodParam)) {
    return NextResponse.json({ error: "period must be YYYY-MM" }, { status: 400 });
  }

  // Distinct periods (rows are few: accounts × 3 per month).
  const { data: periodRows, error: pErr } = await supabase
    .from("monthly_reports")
    .select("period")
    .eq("user_id", user.id)
    .order("period", { ascending: false });
  if (pErr) {
    // Migration not run yet — degrade gracefully. Supabase surfaces a missing
    // table as PGRST205 "Could not find the table ... in the schema cache"
    // (PostgREST answers from its cache before Postgres can raise 42P01).
    const missingTable =
      pErr.code === "42P01" || pErr.code === "PGRST205" || /schema cache/i.test(pErr.message ?? "");
    if (missingTable) {
      return NextResponse.json({ periods: [], period: null, reports: [], needsMigration: true });
    }
    return NextResponse.json({ error: pErr.message }, { status: 500 });
  }
  const periods = [...new Set((periodRows ?? []).map((r) => r.period as string))];
  const period = periodParam ?? periods[0] ?? null;
  if (!period) return NextResponse.json({ periods, period: null, reports: [] });

  const { data: reports, error } = await supabase
    .from("monthly_reports")
    .select("account,report_type,payload,generated_at")
    .eq("user_id", user.id)
    .eq("period", period)
    .order("account");
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  return NextResponse.json({ periods, period, reports: reports ?? [] });
}
